# .github/workflows/checker-script.yml

name: Run Checker Script

on:
  schedule:
    # Run every 2 minutes
    - cron: '*/2 * * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Time
        id: time-check
        run: |
          # Get current time in GMT+6
          current_time=$(TZ='Asia/Dhaka' date '+%H:%M')
          start_time="07:30"
          end_time="11:30"
          
          # Convert times to minutes for comparison
          current_mins=$(TZ='Asia/Dhaka' date '+%H*60+%M' | bc)
          start_mins=$(echo "07*60+30" | bc)
          end_mins=$(echo "11*60+30" | bc)
          
          if [ $current_mins -ge $start_mins ] && [ $current_mins -le $end_mins ]; then
            echo "Time check passed"
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "Outside operating hours (${current_time})"
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v3
        if: steps.time-check.outputs.should_run == 'true'

      - name: Set up Python
        if: steps.time-check.outputs.should_run == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: steps.time-check.outputs.should_run == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install httpx requests

      - name: Run script
        if: steps.time-check.outputs.should_run == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python your_script.py
